### ISSUE TITLE
Search isn't always showing results

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#50]
Testing on my profile today, has often not yielded any search results -- even for schools that are in the database.
![image](https://user-images.githubusercontent.com/5090275/35537136-6d2bf3b0-0506-11e8-8736-005b97557894.png)

This may be part of the reason for a lot of schools being added that are in NCES.

**Comment by mattpen** [comment]
I'm still not quite sure why this is happening.  I've added some extra logging that will help pin it down upon the next deploy.

My hypothesis is that it is due to a performance bottleneck with searches on the server, which relies heavily on regex matching.  I've added indexing and removed the ability to search for partial matches within words.  I've also added special handling for hyphens, periods, slashes and a few other punctuation marks to allow for partial matches at natural word divisions.  

There is still some work left to do to get decimal separated words matched and tokenized correctly.

**Comment by phet-steele** [comment]
It's always showing results for me, what about you @oliver-phet?

**Comment by mattpen** [comment]
These changes were deployed.  I haven't observed this behavior in production yet since the change, but we should continue to monitor it.

**Comment by mattpen** [comment]
@oliver-phet - I haven't seen this behavior again yet.  Are we still seeing a lot of duplicate NCES entries?

I did notice one the other day.  It was for a remote branch of Penn State University.  The user didn't type in university (or a substring of it), so they got more than 20 results.  Their school didn't show up in hte list because we are only sending 20 at a time, so they made a custom school.  I'm thinking we should bump the number of results up to 40 or 60, and this should be tolerable performance-wise.  Sound OK?

**Comment by oliver-phet** [comment]
Still getting a pretty good amount. Here's about 15 minutes of going through US schools needing validation:
![image](https://user-images.githubusercontent.com/5090275/36215813-5b0e93ca-116a-11e8-9954-7cfd377dcd2c.png)
![image](https://user-images.githubusercontent.com/5090275/36215828-6622463a-116a-11e8-8002-d1b35a4efae7.png)
7BooyvHYg3E2DxezL
![image](https://user-images.githubusercontent.com/5090275/36215939-adac5a18-116a-11e8-83bf-db833023a3eb.png)
![image](https://user-images.githubusercontent.com/5090275/36215971-ca18b566-116a-11e8-9bbb-8191327a5a3c.png)
![image](https://user-images.githubusercontent.com/5090275/36216157-33dd81b6-116b-11e8-961a-e8bcced6da98.png)
![image](https://user-images.githubusercontent.com/5090275/36216227-655ee1a8-116b-11e8-8128-aec3598d75dd.png)
![image](https://user-images.githubusercontent.com/5090275/36216276-893083ac-116b-11e8-8847-f4e9d8220367.png)

**Comment by mattpen** [comment]
I've bumped up the limit to 50.  This change will be deployed as soon as the admin edit profile changes are finished.

**Comment by mattpen** [comment]
I haven't noticed any further instances of this problem.  Further improvements to search are being addressed in new issues, closing.
