### ISSUE TITLE
Check duplicate entries when new schools/orgs are added

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#54]
@mattpen Could we add a step to a new school/organization entry that checks if we already have a duplicate entry in our school/org database that matches perfectly (case-insensitive) in the same City and State? Then, instead of adding the new school/org it would simply match them with the existing entry.

**Comment by mattpen** [comment]
Yes this should be possible.  I'll work on it tonight.

**Comment by mattpen** [comment]
@phet-steele, @oliver-phet - on-dev should now be preventing (case-insensitive) exact duplicate entries.  I've tried to insert "Fairview High School, Boulder, Colorado, United States" both in the register and edit profile cases and it seems to be working.  (This is a good use case because the original is "FAIRVIEW HIGH SCHOOL, BOULDER, Colorado, United States"). 

I haven't added any logic like this to the update procedure, but updates are only possible on the admin pages.  

@phet-steele - can you please test and confirm?

**Comment by phet-steele** [comment]
Testing looks gooooood!
