### ISSUE TITLE
Registration Page Improvement: Increase % of matched schools / Lower by-hand matching

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website-meteor#55]
Hi Matt, Oliver is having to match a good number of registrations to schools still by hand. He and I discussed a few options for increasing the % of registrations where the schools are match, and requiring fewer by-hand matches. I'd like to get the by-hand matching down to less than 10% of all registrations, and preferably less than 5% of all registrations. (for US schools). 

A few possibilities are (not sure of how hard each is): 
**Option 1:** If teachers "add there school", have the code do a pre-check, to see if there is a close match - and if so, ask them if it is there school first. (Could think about a design that allows for multiple close matches). Like a pop up dialog that says, you are adding (their info), is this a match to your school (best match). Then a "No, Add my school), or a "Yes, this is my school"). Sort of like when websites ask you about your address. 

**Option 2:** Redesign the School entry spot, so before they type school name, it asks for School City and State in separate fields so that by the time they get to school name, the suggestions can be more narrowed. It seems like for popular school names like "Washington High School" there are perhaps just too many possibilities and people are not picking up to keep going by adding their city in the open box. 

Other options?

**Comment by kathy-phet** [comment]
@mattpen - This is relatively high priority, so it would be great to know your thoughts. We don't want to send the email to everyone, until the percentage of hand-matching is lower. Thx.

**Comment by mattpen** [comment]
@kathy-phet @oliver-phet - We could potentially do both of these solutions.  Here are my thoughts on each.

> have the code do a pre-check, to see if there is a close match

The main problem to solve for Option 1 is to decide what defines a "close match".  Matching City/State/Country is relatively straight forward, but what is "close" in terms of the name of the school?  We could use a threshold on "edit distance" which is a measure of the minimum number of letter edits between two strings (this is a fairly common solution for string similarity problems).  Or we could use a threshold on the number of whole words in common.  Or we could add a list of human defined rewrite rules to help match, like rewriting "HS"->"HIGH SCHOOL" and "MS"->"MIDDLE SCHOOL".  Or we could use a combination of these, and there are other solutions as well.  This is a fairly complex problem and probably requires some thoughtful discussion.  I can't give an estimate on time to completion until this is better defined. 

> Redesign the School entry spot, so before they type school name, it asks for School City and State in separate fields so that by the time they get to school name

We would need to ask for Country as well in order to get a list of acceptable States.  I think this would work well as a modal popup similar in design to the "Add School" dialog.  Would we still use the AutoSuggest box but only do matches on the Name?  Option 2 is more clear than 1 in terms of requirements but would still take a week or two to get it working because it requires changes to the user interface and the database indexing and searching algorithms.

**Comment by kathy-phet** [comment]
Hi Matt, This is sort of what I was thinking for Option 2. I think these could just be temporary parameters (e.g. not stored anywhere except for in the page and informing the search). Best would be if they could be required before you start typing in the name field or something. 

There are some other options, that Oliver and I just discussed. He will connect with you to examine the options. 

One thing I think is nice about this option, is that if someone has already filled out country, state, city and then goes to type "Washington" they get suggestions before they hit the words that can cause non-matches like School vs Sch.

![image](https://user-images.githubusercontent.com/5096804/36691578-fe987d8a-1af2-11e8-8934-95c6d94e3a77.png)

I'm in favor of something you deem an easier solution (e.g. Option 2) since we do need to get this making more matches soon, so we can then send out the email to teachers still within a week or two.

**Comment by mattpen** [comment]
@oliver-phet and I discussed additional possibilities.

1. We should do a mapping of acronyms to words in the database, i.e. "H S" -> "High School" and "HS" -> "High School"
2. We should gather better statistics on the success rates of people adding schools using existing entries.
3. We should implement a priority sorting on the client side so that schools with exact matches for the search string appear first in the list.
4. As an alternative to option 2 above, we could add better instructions to the auto suggest box:
![image](https://user-images.githubusercontent.com/11747676/36701948-679af492-1b12-11e8-9f8e-dc61175efa48.png)
This doesn't help with searches like "New York High School" for instance though.
5. We discussed a different flow for the "Can't find your school" link, which takes you first to an "advanced search" type modal similar to what kathy describe in Option 2, and has a link to the "Add Your School Modal" which behaves like it does now.

**Comment by oliver-phet** [comment]
“EL”: Elementary
“ELEM”: Elementary
“Sch”: School
“H S”: High School
"HS": High School
“MS”: Middle School
“Mdle”: Middle
“J H”: Junior High
“CTR”: Center
“ST”~:~ Saint

**Comment by mattpen** [comment]
@oliver-phet - a first attempt at 1. and 3. from my previous comment are in place on ox-dev.  Some observations and questions are below.

<hr/>

For 3. the sorting order is now :
    
    a. Does the school name include the search string as an exact (case-insensitive) substring?
    b. smallest minimum edit distance
    c. alpha-numeric

I'm inclined to abandon step b. because it tends to just sort strings in terms of length.  This algorithm does a good job of sorting strings that are similar, but if they are very different it just sorts them based on length.  From my tests this seems to be less than helpful.  However, the exact matching is working nicely for the most part, but we might want to add the rules for 1. into the exact matching.  The example I was looking at was "Alternative HS" in San Antonio.  Searches for "Alternative High School" and "Alternative HS" both find it, but the former search places it way down the list and the latter search raises it to the top of the sort order.

<hr/>

For 1. I'm coercing all of the acronyms to the full text version in both the search term and the keyword list in the database (this is a custom field used in search, I'm leaving the NCES name data untouched).  Thus "HS" can now match "High School" and vice versa for example.

<hr/>

I did not implement CTR and ST rewrites as we deemed those to be problematic in our zoom discussion.  However, should we consider "jr" ->"junior" and "sr"->"senior"?

<hr/>

Should we implement 4. as well? It is relatively easy.  We could include those instructions in a (?) button as well, like the Secondary Email Address instructions.

**Comment by oliver-phet** [comment]
I just tried a few tests and 1. seems to help (HS and MS are showing much better results. We may also want to consider adding similar logic to handle state abbreviations ("tx"->"texas").

Yes, I think we should also add "jr" ->"junior" and "sr"->"senior".

I'm ok with abandoning step b. since it sounds like it isn't performing as well. 

I'm not sure step 4. will help much, but it is easy to add. Let's do it in the (?) like you suggested.

**Comment by oliver-phet** [comment]
Here's an odd case... I can't find this school using "cms" as a search term: CHARLES M. SCHENCK (CMS) COMMUNITY SCHOOL

**Comment by oliver-phet** [comment]
Another case for 3.a. "del mar middle school" is listed second (rather than first) in the results?

**Comment by mattpen** [comment]
> Another case for 3.a. "del mar middle school" is listed second (rather than first) in the results?

Hmm.  This is actually a case where 3.b makes sense.  This search fails 3.a because the search is longer than the school's name.  We could change 3.a. to `the search string is a substring of the school's name` OR `the school's name is a substring of the search string`.

**Comment by mattpen** [comment]
> Here's an odd case... I can't find this school using "cms" as a search term: CHARLES M. SCHENCK (CMS) COMMUNITY SCHOOL

This is because the string starts with "(".  We aren't currently removing parentheses/brackets/braces in the tokenization step, but we probably should add these.

**Comment by oliver-phet** [comment]
We may want to do a clean up on the NCES data for Saint Louis, MO.

> SAINT LOUIS
> ST. LOUIS
> ST LOUIS

**Comment by mattpen** [comment]
> We may also want to consider adding similar logic to handle state abbreviations ("tx"->"texas")

MS will be problematic, as it stands for "Middle School" and "Missouri".  I think we would need to assume it means middle school.  We can handle all the other states though.

**Comment by mattpen** [comment]
> We may want to do a clean up on the NCES data for Saint Louis, MO.
>
>> SAINT LOUIS
>> ST. LOUIS
>> ST LOUIS

We are already handling the ".", so this case would just become "st louis"->"saint louis".

**Comment by mattpen** [comment]
> Here's an odd case... I can't find this school using "cms" as a search term: CHARLES M. SCHENCK (CMS) COMMUNITY SCHOOL

I think this has to do with an error in the way I initialized the keywords.  I'm planning to rerun them from scratch when these changes are deployed, so this shouldn't be a problem.  This should generate the keyword list ['charles','cms','community','m','school'] (plus the city/state/county).

**Comment by mattpen** [comment]
@oliver-phet - On ox-dev I've deployed updates for jr/sr/us states/parentheses/apostrophes/st louis/etc.  I also removed the minimum edit distance sorting and added the reflective logic from https://github.com/phetsims/website-meteor/issues/55#issuecomment-368980125.  Please take another look when you get a chance.

**Comment by oliver-phet** [comment]
It seems like 'st' is still difficult to search -- "Saint Martin" doesn't find "ST MARTIN DE PORRES HIGH SCHOOL".

**Comment by oliver-phet** [comment]
Also searching "st.georges" doesn't seem to follow 3.a. (there are schools higher in the search results that don't contain the exact string "saint/st/st. georges").

**Comment by oliver-phet** [comment]
Another special character we should handle: "-". Ex: "tri-county" vs "tricounty".

**Comment by mattpen** [comment]
> Another special character we should handle: "-". Ex: "tri-county" vs "tricounty".

We should be handling this already as a delimiter "tri-county" -> "tri", "county".  It seems sometimes it should be a delimiter and sometimes it should be filtered, we can do both in the keywords on the server side and only use it as a delimiter in the search tokenizer, would that work?

**Comment by kathy-phet** [comment]
I can't really think of "Street" being a common abbreviation in this context of a school name?

**Comment by mattpen** [comment]
ST isn't a common abbreviation for street in school names, but it is used (probably 1% or less of uses of st based on the sample I looked at)

**Comment by oliver-phet** [comment]
> We should be handling this already as a delimiter "tri-county" -> "tri", "county". It seems sometimes it should be a delimiter and sometimes it should be filtered, we can do both in the keywords on the server side and only use it as a delimiter in the search tokenizer, would that work?

I'm not sure I'm following... filter: "tri-county" -> "tricounty" and delimiter: "tri-county" -> "tri county"? And you are saying we can have both "tricounty" and "tri county" include in the search results?

**Comment by mattpen** [comment]
> And you are saying we can have both "tricounty" and "tri county" include in the search results?

Right, I'd need to add some special handling for cases like this, but here's the gist of how it would work for this example.

1.  The keyword generator detects the word "tri-county" and yields the keywords "tri", "county", and "tricounty".
2.  Search use cases:
    1. The search tokenizer detects the word "tri-county" and generates the tokens "tri" and "county".  thus it would match the set of keywords from 1.  
    1.  The search tokenizer detects the words "tri" and "county" and generates "tri" and "county", which matches 1.
    1. The search tokenizer detects the word "tricounty" and generates "tricounty" which matches 1.


Does this make sense?

**Comment by oliver-phet** [comment]
I also did a quick "st" search and there are a few non-saint cases:
COLLEGE ST EL (street)
AUSTIN ST HOSPITAL (state)

**Comment by oliver-phet** [comment]
> Does this make sense?

Sort of... I suppose as long as a "tricounty" search yields "tri county", "tri-county", "and "tricounty" _and_ the inverse is also true, we're probably covering all our bases?

**Comment by mattpen** [comment]
> Sort of... I suppose as long as a "tricounty" search yields "tri county", "tri-county", "and "tricounty" and the inverse is also true, we're probably covering all our bases?

There are two cases that would not match.  A search for "tricounty" will not match a school name with "tri county" and a search for "tri county" will not match a school name with "tricounty".  A search for "tri-county" would match all 3, a search for "tricounty" would match "tri-county" and "tricounty", and a search for "tri county" would match "tri county" and "tri-county".

In order to make the remaining two matches we would need to start detecting compound words and separating their roots into keywords and reverse the problem in the search tokenizing ... this is a VERY difficult problem to handle in the general case.  We can handle a few hand written cases (say less than 100) if needed.

**Comment by oliver-phet** [comment]
Oh right, sorry! Yes the behavior you're describing sounds good.

**Comment by oliver-phet** [comment]
@kathy-phet It looks like we are gradually improving the percentage of matched schools. In the last 2 days, we had an average of 4.20% non-matched US schools (user added). Do you think this is good enough to send out an update profile email to US users or would you like to pursue additional search enhancements (advanced search)?

**Comment by mattpen** [comment]
@oliver-phet - can this be closed?
